### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Casper1131** [Jihell/LibraryRBTree#1]
This would be a great addition
//
    public function getMin(Node $node = null){
        
        if (null === $node) {
            $node = $this->root;
        }
        $min = $this->root;
        while($node->haveChild(Node::POSITION_LEFT)){
        	if($this->compare($node->getChild(Node::POSITION_LEFT),$node)==1){
        		$min = $node->getChild(Node::POSITION_LEFT);
        	}
        	$node = $min;
        }
        return $min;
    }
    //
    public function getMax(Node $node = null){
        
        if (null === $node) {
            $node = $this->root;
        }
	$max = $this->root;
        while($node->haveChild(Node::POSITION_LEFT)){
        	if($this->compare($node->getChild(Node::POSITION_RIGHT),$node)==(-1)){
        		$max = $node->getChild(Node::POSITION_RIGHT);
        	}
        	$node = $max;
        }
        return $max;
    }

**Comment by Jihell** [comment]
Agreed ! Feel free to submit a pull request

**Comment by Jihell** [comment]
Thanks to jcluox
